# Generated by Django 3.2.15 on 2022-09-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
    ]
